module.exports = class UserExtended {
    Language = 0;
    Urls = [];
    LookingFor = 0;
    DateOfBirth = 0;
    Relationship = 0;
    Gender = 0;
    About = '';
    OptOut = null;
    UtfOffset = 0;
    Latitude = 0;
    Longitude = 0;
    Name1 = null;
    After = null;
    DobD = 0;
    DobM = 0;
    DobY = 0;
    RelationshipStatus = 0;
    Sex = 0;
    Name = null;
}